---
dist: xenial
sudo: required
group: bluezone
language: generic

# Environment variables (setup endpoint to IBM github)
env:
  global:
  - OCTOKIT_API_ENDPOINT="https://github.ibm.com/api/v3/"

before_install:
  # Clone build tools & set tools path for follow on processing
  # The clone command will use the ssh key from the travis settings to clone the repo from github.ibm.com
  - if [[ ! -z "$BRANCH_OVERRIDE" ]] ; then
      git clone -b $BRANCH_OVERRIDE git@github.ibm.com:ibmprivatecloud/content-tools;
    else 
      git clone git@github.ibm.com:ibmprivatecloud/content-tools;
    fi
  - export toolsPath=`pwd`/content-tools/travis-tools/
  # Install dependencies & determine chart delta - true set for debug
  - $toolsPath/build/bin/installDependencies.sh | true
  - export changeList=`$toolsPath/build/bin/determineChartDelta.sh | tee determineChartDelta.out | grep 'return determineChartDelta:' | cut -f2 -d:` && cat determineChartDelta.out
  - source travis-env.sh
   
install:
  # Package for release 
  - if [[ ! -z "$TRAVIS_TAG" ]] ; then $toolsPath/release/bin/package.sh; fi
  - helm install --dry-run --debug --values cv-tests/test-01/values.yaml
  # Lint and install/test charts (if cv-tests exist)
  - $toolsPath/cv-test/bin/validateContent.sh | true
  - docker info


deploy:
  # scp helm repo(s) to location identified (Note: SSHPASS env variable must contain password)
  - provider: script
    skip_cleanup: true
    script:  $toolsPath/build/bin/deployHelmRepo.sh
    on:
      all_branches: true
  # Publish tagged release
  - provider: releases
    skip_cleanup: true
    api_key: $GITHUB_TOKEN
    file_glob: true
    file: repo/stable/*
    on:
      tags: true

os:
  - linux

services:
  - docker

branches:
  only:
    - master
    - /^[0-9]+\..*$/
    - /^v[0-9]+\..*$/
    - /^release-[0-9]+\..*$/
    - /^([^[:space:]]+)-ga-20[1,2][0-9]-([0][1-9]|[1][0-2])-[0-3][0-9]/
    - /^([^[:space:]]+-|)ga-0000-00-00(-[^[:space:]]+/


before_script:
  - make tool
  - make init
  - make lint

script:
  - make build
  - test "$TRAVIS_EVENT_TYPE" = "pull_request" && make push || echo "not pushing to scratch"
  - test "$TRAVIS_EVENT_TYPE" != "pull_request" && make publish || echo "not pushing to integration"
  - echo "Override default script"
