os:
  - linux

services:
  - docker

branches:
  only:
    - 3.2.1
    - master
    - /^[0-9]+\..*$/
    - /^v[0-9]+\..*$/
    - /^release-[0-9]+\..*$/

before_install:
  - source travis-env.sh

install:
  - docker info

before_script:
  - make tool
  - make lint

script:
  - make build
  - test "$TRAVIS_EVENT_TYPE" = "pull_request" && make push || echo "not pushing to scratch"
  - test "$TRAVIS_EVENT_TYPE" != "pull_request" && make publish || echo "not pushing to integration"
