# Licensed Materials - Property of IBM
# 5737-E67
# (C) Copyright IBM Corporation 2016, 2019 All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

apiVersion: v1
kind: Service
metadata:
  name: {{ template "search.fullname" . }}-searchapi
  labels:
    app: {{ template "search.name" . }}
    component: "searchapi"
    chart: {{ template "search.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
    - port: 4010
      targetPort: 4010
      protocol: TCP
      name: http
  selector:
    app: {{ template "search.name" . }}
    component: "searchapi"
    release: {{ .Release.Name }}
