# Licensed Materials - Property of IBM
# 5737-E67
# (C) Copyright IBM Corporation 2016, 2019 All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

# apiVersion: certmanager.k8s.io/v1alpha1
# kind: Certificate
# metadata:
#   name: {{ template "console.fullname" . }}-ca-cert
#   labels:
#     app: {{ template "console.name" . }}
#     chart: {{ template "console.chart" . }}
#     release: {{ .Release.Name }}
#     component: "mcmuiapi"
#     heritage: {{ .Release.Service }}
# spec:
#   secretName: {{ template "console.fullname" . }}-uiapi-secrets
#   issuerRef:
#     name: {{ .Release.Name }}-mcm-server-ca-issuer
#     kind: Issuer
#   commonName: {{ template "console.fullname" . }}
#   dnsNames: null
#   isCA: true
#   organization:
#   - IBM
