# Licensed Materials - Property of IBM
# 5737-E67
# (C) Copyright IBM Corporation 2016, 2019 All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

# apiVersion: v1
# kind: Service
# metadata:
#   name: {{ template "console.fullname" . }}-mcmuiapi
#   labels:
#     app: {{ template "console.name" . }}
#     component: "mcmuiapi"
#     chart: {{ template "console.chart" . }}
#     release: {{ .Release.Name }}
#     heritage: {{ .Release.Service }}
# spec:
#   ports:
#     - port: 4000
#       targetPort: 4000
#       protocol: TCP
#       name: http
#   selector:
#     app: {{ template "console.name" . }}
#     component: "mcmuiapi"
#     release: {{ .Release.Name }}
