name: ibm-search-prod
description: Search Helm Chart for IBM Multicloud Manager
version: 3.4.0
icon: https://raw.githubusercontent.com/kubernetes/kubernetes/master/logo/logo.png
tillerVersion: ">=2.7.3"
kubeVersion: '>=1.10.0'
appVersion: '3.4.0'
keywords:
- ICP
- multicluster
- search
- Commercial
- amd64
- ppc64le
- s390x
- runtime