name: ibm-search-prod
description: Search Helm Chart for IBM Cloud Pak for Multicloud Management
version: 3.5.0
icon: https://raw.githubusercontent.com/kubernetes/kubernetes/master/logo/logo.png
tillerVersion: ">=2.9.0"
kubeVersion: '>=1.10.0'
appVersion: 3.4.0
keywords:
- ICPRHOCP
- multicluster
- search
- Commercial
- amd64
- ppc64le
- s390x
- runtime
