# Licensed Materials - Property of IBM
# 5737-E67
# (C) Copyright IBM Corporation 2016, 2019 All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.search.fullname }}-search-redisgraph
  labels:
    app: {{ .Values.search.name }}
    component: "mcm-search"
    chart: {{ .Values.search.chart }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
    - name: redisgraph
      protocol: TCP
      port: 6380
      targetPort: 6380
  selector:
    app: {{ .Values.search.name }}
    component: "redisgraph"
    release: {{ .Release.Name }}
